# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !
#
# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

#export PS1="[\u@\h \W]\\$ \[$(tput sgr0)\]"
export PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\$ "
export EDITOR=nano
export HISTCONTROL=ignoreboth

#export VAGRANT_LOG=debug
#export VAGRANT_DEFAULT_PROVIDER="libvirt"

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias dotdrop='~/dotdrop-files/dotdrop.sh --cfg=~/dotdrop-files/config.yaml'

# dircolors
eval `dircolors ~/.dir_colors`

# ssh keys
eval `ssh-agent` 1>/dev/null 2>&1
ssh-add ~/.ssh/id_rsa 1>/dev/null 2>&1
ssh-add ~/.ssh/id_ed25519 1>/dev/null 2>&1
ssh-add ~/sshkeys/github/einwolf_ed25519 1>/dev/null 2>&1
