config:
  backup: true
  create: true
  dotpath: dotfiles
  banner: false
  longkey: true
dotfiles:
  f_nanorc:
    src: nanorc
    dst: ~/.nanorc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_logout:
    src: bash_logout
    dst: ~/.bash_logout
  f_inputrc:
    src: inputrc
    dst: ~/.inputrc
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    chmod: '644'
  f_config_yapf_style:
    src: config/yapf/style
    dst: ~/.config/yapf/style
profiles:
  default:
    dotfiles:
    - f_nanorc
    - f_bash_profile
    - f_bashrc
    - f_bash_logout
    - f_inputrc
    - f_dir_colors
    - f_ssh_config
    - f_config_yapf_style
  strongbox:
    include:
    - default
  arcnova:
    include:
    - default
  axiom:
    include:
    - default
  direflare:
    include:
    - default
  duality:
    include:
    - default
  horizon:
    include:
    - default
  radiance:
    include:
    - default
  ZephyrusG14:
    include:
    - default
  ZephyrusG15:
    include:
    - default
